### ISSUE TITLE
공방 UI

### ISSUE THREAD

**Issue by YewonHwangeayo** [The-Sculptor/Sculptor-Andorid#8]
## ✅ Todo 

- [ ] 기본 화면 만들기
- [ ] 오늘의 달성 기록 화면 만들기 (세부화면)
- [ ] 돌 기록하기 화면 2개 만들기
- [ ] 새로운 돌 생성 화면 만들기
