### ISSUE TITLE
박물관 ui 작업

### ISSUE THREAD

**Issue by HwangSeo** [The-Sculptor/Sculptor-Andorid#9]
## ✨ About Issue ✨
박물관 ui 작업

<br>

## ✅ Todo 

- [ ] 기본 박물관 화면
- [ ] 프로필 편집 화면
- [ ] 조각상 대표화면
- [ ] 조각상 클릭했을 때 정보화면
